-- Complete fix for database registration error
-- Run this script in Supabase SQL Editor

-- STEP 1: Make invited_by field NULLABLE (it was incorrectly set as NOT NULL)
ALTER TABLE public.profiles 
ALTER COLUMN invited_by DROP NOT NULL;

-- STEP 2: Drop and recreate the user creation trigger with proper error handling
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  inviter_id UUID;
BEGIN
  -- Safely extract inviter_id from metadata, allow NULL
  BEGIN
    inviter_id := (new.raw_user_meta_data->>'invited_by')::uuid;
  EXCEPTION WHEN OTHERS THEN
    inviter_id := NULL;
  END;

  -- Insert profile (invite_code will be auto-generated by trigger_auto_generate_invite_code)
  INSERT INTO public.profiles (id, username, avatar_url, invited_by)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'username', SPLIT_PART(new.email, '@', 1)),
    'https://api.dicebear.com/7.x/initials/svg?seed=' || COALESCE(new.raw_user_meta_data->>'username', SPLIT_PART(new.email, '@', 1)),
    inviter_id
  );
  
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Recreate trigger
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- STEP 3: Verify the fix
-- Check if invite_code trigger exists
SELECT trigger_name, event_manipulation, event_object_table
FROM information_schema.triggers
WHERE trigger_name = 'trigger_auto_generate_invite_code';

-- Check current schema
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'profiles' 
  AND column_name IN ('invite_code', 'invited_by');

-- Success message
DO $$
BEGIN
  RAISE NOTICE 'Database fix applied successfully!';
  RAISE NOTICE 'You can now register new users.';
END $$;
