-- Fix: Update trigger to work with auto-generated invite_code
-- The invite_code will be auto-generated by trigger_auto_generate_invite_code
-- This trigger only needs to set basic profile info

-- Drop existing trigger and function
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

-- Create updated function - let invite_code be auto-generated
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  inviter_id UUID;
BEGIN
  -- Try to get inviter_id from metadata, allow NULL
  BEGIN
    inviter_id := (new.raw_user_meta_data->>'invited_by')::uuid;
  EXCEPTION WHEN OTHERS THEN
    inviter_id := NULL;
  END;

  INSERT INTO public.profiles (id, username, avatar_url, invited_by)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'username', SPLIT_PART(new.email, '@', 1)),
    'https://api.dicebear.com/7.x/initials/svg?seed=' || COALESCE(new.raw_user_meta_data->>'username', SPLIT_PART(new.email, '@', 1)),
    inviter_id
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Recreate trigger
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

COMMENT ON FUNCTION public.handle_new_user() IS 'Automatically creates profile with invited_by relationship. invite_code is auto-generated by trigger_auto_generate_invite_code';
